/**
 * Do not edit directly, this file was auto-generated.
 */

export const PrimaryNormal = '#0066ff'
export const PrimaryStrong = '#005eeb'
export const PrimaryHeavy = '#0054d1'
export const LabelNormal = '#171719'
export const LabelStrong = '#000000'
export const LabelNeutral = '#2e2f33'
export const LabelAlternative = '#37383c'
export const LabelAssistive = '#37383c'
export const LabelDisable = '#37383c'
export const BackgroundNormalNormal = '#ffffff'
export const BackgroundNormalAlternative = '#f7f7f8'
export const BackgroundElevatedNormal = '#ffffff'
export const BackgroundElevatedAlternative = '#f7f7f8'
export const InteractionInactive = '#989ba2'
export const InteractionDisable = '#f4f4f5'
export const LineNormalNormal = '#70737c'
export const LineNormalNeutral = '#70737c'
export const LineNormalAlternative = '#70737c'
export const LineNormalStrong = '#70737c'
export const LineSolidNormal = '#e1e2e4'
export const LineSolidNeutral = '#eaebec'
export const LineSolidAlternative = '#f4f4f5'
export const LineSolidStrong = '#aeb0b6'
export const FillNormal = '#70737c'
export const FillStrong = '#70737c'
export const FillAlternative = '#70737c'
export const StatusPositive = '#00bf40'
export const StatusCautionary = '#ff9200'
export const StatusNegative = '#ff4242'
export const StaticWhite = '#ffffff'
export const StaticBlack = '#000000'
export const AccentLime = '#58cf04'
export const AccentCyan = '#00bdde'
export const AccentLightBlue = '#00aeff'
export const AccentViolet = '#6541f2'
export const AccentPink = '#f553da'
export const AccentRedOrange = '#ff5e00'
export const AccentPurple = '#cb59ff'
export const MaterialDimmer = '#171719'
export const InversePrimary = '#3385ff'
export const InverseBackground = '#1b1c1e'
export const InverseLabel = '#f7f7f8'
