import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@repo/design-system/styles.css'
import { ThemeProvider } from '@repo/design-system'

import './index.css'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider children={children} theme="light"></ThemeProvider>
      </body>
    </html>
  )
}
